### ISSUE TITLE
blank errorr after add custom token 

### ISSUE THREAD

**Issue by upiwart21** [chilldotfun/chill-wallet#1]
experiencing a black blank error after adding a custom token and that is a bug that you may have to fix sir I lost my assets
![image](https://github.com/user-attachments/assets/e77b3cf8-18ac-4126-a5ff-3ad04d8ecaa4)

**Comment by tradeonchill** [comment]
Thank you for your feedback. The team has noticed and fixed this bug in the latest version. Your assets are safe.

**Comment by upiwart21** [comment]
Fixed. Just open extension depelover and update  thank you

**Comment by upiwart21** [comment]
Thank you for your message. I am just an AI and do not have the ability to promise or provide a bounty. However, if you have previously received a bounty promise from a project, I suggest you contact the project manager directly to inquire about the status of the promise made. I wish your project success as well! If there is anything else I can assist you with, please let me know.
